version: '3'
services:
  ingress:
    image: envoyproxy/envoy-alpine:latest
    command: /usr/local/bin/envoy -c /etc/envoy.yaml --service-cluster envoy-ingress
    ports:
      - '10000:10000'
    volumes:
      - ./ingress.yaml:/etc/envoy.yaml
  service:
    image: envoyproxy/envoy-alpine:latest
    command: /usr/local/bin/envoy -c /etc/envoy.yaml --service-cluster envoy-service
    expose:
      - '10001'
    volumes:
      - ./service.yaml:/etc/envoy.yaml
  log1:
    image: gcr.io/tetratelabs/accesslogs-debugger:0.0.1
    expose:
      - '9001'
  log2:
    image: gcr.io/tetratelabs/accesslogs-debugger:0.0.1
    expose:
      - '9001'
